# thinker_prompt.yaml

# System prompts
idea_system_prompt: >
  You are an ambitious AI PhD student who is looking to publish a paper that will contribute significantly to the field.
  You want to generate creative and impactful research ideas that can be feasibly investigated with the code provided.
  Be critical and realistic in your assessments.

novelty_system_prompt: |
  You are an ambitious AI PhD student who is looking to publish a paper that will contribute significantly to the field.
  You have an idea and you want to check if it is novel or not. I.e., not overlapping significantly with existing literature or already well explored.
  Be a harsh critic for novelty, ensure there is a sufficient contribution in the idea for a new conference or workshop paper.
  You will be given access to the Semantic Scholar API, which you may use to survey the literature and find relevant papers to help you make your decision.
  The top 10 results for any search query will be presented to you with the abstracts.

  You will be given {num_rounds} to decide on the paper, but you do not need to use them all.
  At any round, you may exit early and decide on the novelty of the idea.
  Decide a paper idea is novel if after sufficient searching, you have not found a paper that significantly overlaps with your idea.
  Decide a paper idea is not novel, if you have found a paper that significantly overlaps with your idea.

# Complete prompts that combine all necessary information
idea_first_prompt: |
  Here are the ideas that you have already generated:

  '''
  {prev_ideas_string}
  '''

  {pdf_section}

  Additionally, based on recent literature, here are some related works that might inform your next idea:

  ```
  {related_works_string}
  ```

  Based on the above, come up with the next impactful and creative idea for research experiments and directions you can feasibly investigate with the code provided.
  Note that you will not have access to any additional resources or datasets.
  Make sure any idea is not overfit to the specific training dataset or model, and has wider significance.

  Respond in the following format:

  THOUGHT:
  <THOUGHT>

  NEW IDEA JSON:
  ```json
  <JSON>
  ```

  In <THOUGHT>, first briefly discuss your intuitions and motivations for the idea. Detail your high-level plan, necessary design choices and ideal outcomes of the experiments. Justify how the idea is different from the existing ones.

  In <JSON>, provide the new idea in JSON format with the following fields:
  - "Name": A shortened descriptor of the idea. Lowercase, no spaces, underscores allowed.
  - "Title": A title for the idea, will be used for the report writing.
  - "Experiment": An outline of the implementation. E.g. which functions need to be added or modified, how results will be obtained, ...
  - "Interestingness": A rating from 1 to 10 (lowest to highest).
  - "Feasibility": A rating from 1 to 10 (lowest to highest).
  - "Novelty": A rating from 1 to 10 (lowest to highest).
  - "Score": Your assessment of this idea on the standard 1-10 ML conference scale.

  Be cautious and realistic on your ratings.
  This JSON will be automatically parsed, so ensure the format is precise.
  You will have {num_reflections} rounds to iterate on the idea, but do not need to use them all.

  Completed ideas have an additional "Score" field which indicates the assessment by an expert ML reviewer.
  This is on a standard 1-10 ML conference scale.
  Scores of 0 indicate the idea failed either during experimentation, writeup or reviewing.

idea_reflection_prompt: |
  Round {current_round}/{num_reflections}.

  In your thoughts, first carefully consider the quality, novelty, and feasibility of the idea you just created.
  Refer to the following related works from recent literature that might help inform your reflection:

  ```
  {related_works_string}
  ```

  Include any other factors that you think are important in evaluating the idea.
  Ensure the idea is clear and concise, and the JSON is the correct format.
  Do not make things overly complicated.
  In the next attempt, try and refine and improve your idea.
  Stick to the spirit of the original idea unless there are glaring issues.

  Respond in the same format as before:
  THOUGHT:
  <THOUGHT>

  NEW IDEA JSON:
  ```json
  <JSON>
  ```

  If there is nothing to improve, simply repeat the previous JSON EXACTLY after the thought and include "I am done" at the end of the thoughts but before the JSON.
  ONLY INCLUDE "I am done" IF YOU ARE MAKING NO MORE CHANGES.

novelty_prompt: |
  Round {current_round}/{num_rounds}.
  You have this idea:

  """
  {idea}
  """

  The results of the last query are (empty on first round):
  """
  {last_query_results}
  """

  Respond in the following format:

  THOUGHT:
  <THOUGHT>

  RESPONSE:
  ```json
  <JSON>
  ```

  In <THOUGHT>, first briefly reason over the idea and identify any query that could help you make your decision.
  If you have made your decision, add "Decision made: novel." or "Decision made: not novel." to your thoughts.

  In <JSON>, respond in JSON format with ONLY the following field:
  - "Query": An optional search query to search the literature (e.g., "attention is all you need"). You must generate a query if one has not been decided this round.

  Formatting requirements for the "Query":
    - The query should be a well-formed string that aligns with search capabilities of both **Semantic Scholar** and **OpenAlex** APIs.
    - Prefer exact phrases enclosed in quotes for title-specific searches (e.g., `"attention is all you need"`).
    - Use Boolean operators ("AND", "OR", "NOT") to refine the search when necessary (e.g., `"transformer models" AND "natural language processing"`).
    - Include key terms, author names, or publication years if available (e.g., `"BERT embeddings" AND "Devlin et al." AND year:2018`).
    - Avoid unnecessary special characters or overly generic terms.
    - Use parentheses to group conditions for complex queries (e.g., `"(graph neural networks OR GNN) AND (social network analysis)"`).

  A query will work best if you are able to recall the exact name of the paper you are looking for, or the authors.
  This JSON will be automatically parsed, so ensure the format is precise.
